Serilog:
  MinimumLevel:
    Default: Debug
    Override:
      Microsoft: Warning
      Microsoft.Hosting.Lifetime: Information
  WriteTo:
    - Name: Console
      Args:
        restrictedToMinimumLevel: Information
    - Name: File
      Args:
        path: logs/log-.txt
        rollingInterval: Day
        retainedFileCountLimit: 30
        outputTemplate: "{Timestamp:yyyy-MM-dd HH:mm:ss.fff zzz} [{Level:u3}] {SourceContext} {Message:lj}{NewLine}{Exception}"

AllowedHosts: "*"

ProtheusSettings:
  BaseUrl: "http://187.45.183.238:8091/rest-hom"
  Usuario: "red-api"
  Senha: "!ok$$L8GRb"

JwtSettings:
  Audience: "http://localhost:5010"
  Issuer: "http://localhost:5010"
  Secret: "Elderly-Esophagus-Duly-Blouse8-Lethargy-Unbraided-Opacity"
  DefaultExpirationInHours: 24

SmtpSettings:
  Host: "smtp.redmobile.com.br"
  Port: 465
  EnableSsl: true
  Username: "noreply_portalred@redmobile.com.br"
  Password: ""
  FromName: "Portal RedMobile"
  FromEmail: "noreply_portalred@redmobile.com.br"
