name: portalred

networks:
  portalred-net:
    driver: bridge

services:
  backend:
    build:
      context: .
      dockerfile: infra/backend/Dockerfile
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtSettings__Secret=${JWT_SECRET}
      - SmtpSettings__Password=${SMTP_PASSWORD}
      - ProtheusSettings__BaseUrl=${PROTHEUS_BASE_URL}
      - ProtheusSettings__Usuario=${PROTHEUS_USUARIO}
      - ProtheusSettings__Senha=${PROTHEUS_SENHA}
    ports:
      - "127.0.0.1:5000:8080"
    networks:
      - portalred-net

  frontend:
    build:
      context: .
      dockerfile: infra/frontend/Dockerfile
      args:
        VITE_API_URL: ${VITE_API_URL}
        VITE_MAPBOX: ${VITE_MAPBOX}
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "127.0.0.1:3000:80"
    networks:
      - portalred-net
