import { LngLatLike } from "mapbox-gl";

export const estadosBrasileiros = [
    { initials: "AC", name: "Acre" },
    { initials: "AL", name: "Alagoas" },
    { initials: "AP", name: "Amapá" },
    { initials: "AM", name: "Amazonas" },
    { initials: "BA", name: "Bahia" },
    { initials: "CE", name: "Ceará" },
    { initials: "DF", name: "Distrito Federal" },
    { initials: "ES", name: "Espírito Santo" },
    { initials: "GO", name: "Goiás" },
    { initials: "MA", name: "Maranhão" },
    { initials: "MT", name: "Mato Grosso" },
    { initials: "MS", name: "Mato Grosso do Sul" },
    { initials: "MG", name: "Minas Gerais" },
    { initials: "PA", name: "Pará" },
    { initials: "PB", name: "Paraíba" },
    { initials: "PR", name: "Paraná" },
    { initials: "PE", name: "Pernambuco" },
    { initials: "PI", name: "Piauí" },
    { initials: "RJ", name: "Rio de Janeiro" },
    { initials: "RN", name: "Rio Grande do Norte" },
    { initials: "RS", name: "Rio Grande do Sul" },
    { initials: "RO", name: "Rondônia" },
    { initials: "RR", name: "Roraima" },
    { initials: "SC", name: "Santa Catarina" },
    { initials: "SP", name: "São Paulo" },
    { initials: "SE", name: "Sergipe" },
    { initials: "TO", name: "Tocantins" },
];

export const coordenadasEstadosBrasileiros: {[key: string]: LngLatLike} = {
    "AC": [-70, -9],
    "AL": [-36.5, -9.6],
    "AP": [-51.9, 1.4],
    "AM": [-64.0, -4.8, ],
    "BA": [-41.2, -12.8],
    "CE": [-39.4, -5.2],
    "DF": [-47.8, -15.8],
    "ES": [-40.4, -19.6],
    "GO": [-49.7, -15.7],
    "MA": [-45.4, -5.1],
    "MT": [-55.8, -13],
    "MS": [-54.8, -20.4],
    "MG": [-44.4, -18.7],
    "PA": [-52.9, -4.3],
    "PB": [-35.9, -7],
    "PR": [-51.6,-24.6],
    "PE": [-38.1,-8.4],
    "PI": [-42.5,-7.5],
    "RJ": [-42.3,-22.2],
    "RN": [-36.5,-5.5],
    "RS": [-53.1,-29.5],
    "RO": [-63, -10.8],
    "RR": [-61.2, 1.8],
    "SC": [-49.8, -27.3],
    "SP": [-48.7,-22.2],
    "SE": [-37.4,-10.7],
    "TO": [-48.4, -10.1],
};
